name: Test publish YML
description: Test.
author: "André Neto"

runs:
  # The type of runner that the job will run on
  using: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs ls
    - name: Run ls
      run: ls

    # Runs tar the project
    - name: Run a multi-line script
      run: |
        touch workspace.tar.gz
        tar -czf workspace.tar.gz --exclude=workspace.tar.gz .

    # Runs ls
    - name: Run ls
      run: ls

    # Runs a get
    - name: Run get
      run: curl --location --request GET 'https://jsonplaceholder.typicode.com/todos/1'

    # Runs a post
    - name: Run post
      run: |
        curl --location --request POST 'https://jsonplaceholder.typicode.com/posts' \
        --header 'Content-Type: application/json' \
        --data-raw '{
        "title": "foo",
        "body": "bar",
        "userId": 1
        }'

    # Runs a post2
    - name: Run post2
      run: |
        curl --location --request POST 'https://jsonplaceholder.typicode.com/posts' \
        --form '=@"./workspace.tar.gz"'

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
