# This is a basic workflow to help you get started with Actions

name: Test publish YML
descripion: This is an action to assign yourself to an issue for a repo you are not a contributor to.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs ls
      - name: Run ls
        run: ls

      # Runs tar the project
      - name: Run a multi-line script
        run: |
          touch workspace.tar.gz
          tar -czf workspace.tar.gz --exclude=workspace.tar.gz .

      # Runs ls
      - name: Run ls
        run: ls

      # Runs a get
      - name: Run get
        run: curl --location --request GET 'https://jsonplaceholder.typicode.com/todos/1'

      # Runs a post
      - name: Run post
        run: |
          curl --location --request POST 'https://jsonplaceholder.typicode.com/posts' \
          --header 'Content-Type: application/json' \
          --data-raw '{
          "title": "foo",
          "body": "bar",
          "userId": 1
          }'

      # Runs a post2
      - name: Run post2
        run: |
          curl --location --request POST 'https://jsonplaceholder.typicode.com/posts' \
          --form '=@"./workspace.tar.gz"'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
